packages:
  - "packages/bot"
  - "packages/frontend"
allowBuilds:
  '@parcel/watcher': set this to true or false
  bufferutil: set this to true or false
  canvas: set this to true or false
  es5-ext: set this to true or false
  esbuild: set this to true or false
  keccak: set this to true or false
  secp256k1: set this to true or false
  sharp: set this to true or false
  tesseract.js: set this to true or false
  utf-8-validate: set this to true or false
  web3: set this to true or false
  web3-bzz: set this to true or false
  web3-shh: set this to true or false
